config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users
  
  get 'admin_dashboard/index'

  get 'about/howitworks'

  get 'about/aboutus'

  get 'about/terms'

  get 'admin_dashboard/all_bills'

  get 'admin_dashboard/all_users'

  get 'admin_dashboard/phone_data'

  resources :providers

  get 'sendtext/index'

  root "home#index"

  get 'bills/list'

  resources :bills

  resources :categories do
    resources :providers
  end
  
  resources :dashboard
  

  

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :category

  validates :category_id, presence: true
  validates :name, presence: true
  validates :url, presence: true 
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:category_id, :name, :url)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
<% if @provider.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

  <ul>
    <% @provider.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <!-- Drop Down menu for categories -->
  <%= f.label :category_id %><br>
  <%= f.collection_select :category_id, Category.order(:name), :id, :name%>
</div>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :url %><br>
  <%= f.text_field :url %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
    <tr>
      <td><%= provider.category.name %></td>
      <td><%= provider.name %></td>
      <td><%= provider.url %></td>
      <td><%= link_to 'Show', provider %></td>
      <td><%= link_to '', edit_provider_path(provider),class: "fa fa-pencil-square-o" %></td>
      <td><%= link_to provider, method: :delete, data: { confirm: 'Are you sure?' } do%>
        <i class="fa fa-trash-o"></i>
        <%end%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @provider.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @provider.url %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>