config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users
  
  get 'admin_dashboard/index'

  get 'about/howitworks'

  get 'about/aboutus'

  get 'about/terms'

  get 'admin_dashboard/all_bills'

  get 'admin_dashboard/all_users'

  get 'admin_dashboard/phone_data'

  resources :providers

  get 'sendtext/index'

  root "home#index"

  get 'bills/list'

  resources :bills

  resources :categories do
    resources :providers
  end
  
  resources :dashboard
  

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_one :category, through: :provider
  belongs_to :user
  belongs_to :provider
  has_one :event_recurrence, :dependent => :destroy

  #create_event_recurrence creates the actual recurrence and 
  #also calls on send_recurrence at the end of the method
  after_create :create_event_recurrence
  after_destroy :delete_recurrence
  after_update :update_recurrence
  after_update :update_contact_method, :if => :contact_method_changed? 

  
  validates :every, presence: true
  validates :provider_id, presence: true
  validates :user_id, presence: true
  validates :duedate, presence: true
  validates :contact_method, presence: true

  attr_accessor :date

  @@token = "11bbad9f27d1494f8d8570db1ba4855a"

  #search method
	def self.search(search)
  	unless search.blank?
  		search = "%#{search}%"
  		where('Name LIKE ? ', search)
  	else
  		all
  	end
	end

  def create_event_recurrence
    event_recurrence = EventRecurrence.new
    event_recurrence.bill_id = self.id
    event_recurrence.end_date = 1.year.from_now
    event_recurrence.every = self.every
    start = self.duedate

    # recurrence doesn't count now in the time period, so we need to go back 1 interval
    event_recurrence.start_date = 
    case self.every
    when 'year'
    start.last_year
    when 'month'
    start.last_month 
    when 'twice a year'
    start.last_month + 1.month
    when 'every two weeks'
    start - 14.days
    when 'day'
    start.yesterday
    end

    event_recurrence.interval = 
    case self.every
    when 'every two weeks'
    2 #weeks
    when 'twice a year'
    6 #months 
    end

    event_recurrence.save

    send_recurrence
  end

  def dates(options={})
    self.event_recurrence.dates(options)
  end

  def send_recurrence
    begin
    if self.contact_method == 'text'
      HTTParty.post("http://sleepy-citadel-7753.herokuapp.com/texts.json", 
        :body => {
        'event_recurrence' => {
        'object_id' => self.id,
        'end_date' => 1.year.from_now,
        'every' => self.every,
        'start_date' => self.duedate}, 
        'text' => { 
        'cell_phone' => self.user.cell_phone,
        'text_reminder' => "This is a reminder that your #{self.provider.name} bill is due tomorrow. #{self.provider.url}"
        }
        }.to_json, 

        :headers => { 
        'Authorization' => "Token token=#{@@token}",
        'Content-Type' => 'application/json',
        'Accept' => "application/json" } )

    elsif self.contact_method == 'phone call'
      HTTParty.post("http://sleepy-citadel-7753.herokuapp.com/calls.json", 
      :body => {
        'event_recurrence' => {
        'object_id' => self.id,
        'end_date' => 1.year.from_now,
        'every' => self.every,
        'start_date' => self.duedate}, 
        'call' => { 
        'cell_phone' => self.user.cell_phone,
        'call_reminder' => "Hello #{self.user.first_name}. This is a friendly reminder that your #{self.provider.name}, #{self.category.name} bill is due tomorrow. Thank you for using Forget Me Not. GoodBye!"
        }
        }.to_json, 

        :headers => { 
        'Authorization' => "Token token=#{@@token}",
        'Content-Type' => 'application/json',
        'Accept' => "application/json" } )

    elsif self.contact_method == 'email'
      HTTParty.post("http://sleepy-citadel-7753.herokuapp.com/emails.json", 
        :body => {
        'event_recurrence' => {
        'object_id' => self.id,
        'end_date' => 1.year.from_now,
        'every' => self.every,
        'start_date' => self.duedate}, 
        'email' => { 
        'email_address' => self.user.email,
        'email_reminder' => "Hello #{self.user.first_name}. This is a friendly reminder that your #{self.provider.name}, #{self.category.name} bill is due tomorrow. Thank you for using Forget Me Not"

        }
        }.to_json, 

        :headers => { 
        'Authorization' => "Token token=#{@@token}",
        'Content-Type' => 'application/json',
        'Accept' => "application/json" } )
    end
    rescue Exception

    end
  end

  def delete_recurrence
    # a is an array of hashes. each hash being an event recurrence.
    # a.each iterates over every hash in the response array. 
    # if the hash has a key 'object_id' whos value is equal to that of bill.id
    # @match represents the instance on the API that needs to be deleted, when a bill is deleted in ReminderApp
    begin
    response = HTTParty.get("http://sleepy-citadel-7753.herokuapp.com/event_recurrences.json")
    a = JSON.parse(response.body)
    a.each do |hash|
      if hash['object_id'] == self.id.to_s
        @match = hash
      end
    end

    #Does the delete by inputting the instance ID of the object we are attempting to delete
    HTTParty.delete("http://sleepy-citadel-7753.herokuapp.com/event_recurrences/#{@match['id'].to_i}.json", 
      :body => {'object_id' => self.id }.to_json, 

      :headers => { 
      'Authorization' => "Token token=#{@@token}",
      'Content-Type' => 'application/json',
      'Accept' => "application/json" } )

    rescue Exception

    end
  end

  def update_recurrence
    begin
    response = HTTParty.get("http://sleepy-citadel-7753.herokuapp.com/event_recurrences.json")
    a = JSON.parse(response.body)
    a.each do |hash|
      if hash['object_id'] == self.id.to_s
        @match = hash
      end
    end

    HTTParty.patch("http://sleepy-citadel-7753.herokuapp.com/event_recurrences/#{@match['id'].to_i}.json", 
    :body => {'object_id' => self.id,
    'end_date' => self.duedate + 1.year,
    'every' => self.every,
    'start_date' => self.duedate, 
    'cell_phone' => self.user.cell_phone,
    'email' => self.user.email }.to_json, 

    :headers => { 
    'Authorization' => "Token token=#{@@token}",
    'Content-Type' => 'application/json',
    'Accept' => "application/json" } )

    rescue Exception

    end
  end

  #if a bill is updated with a new contact method, 
  #this method will delete the old instance and add a new one with the new contact 
  def update_contact_method
    delete_recurrence
    send_recurrence
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  protect_from_forgery with: :null_session

  # GET /bills
  # GET /bills.json
  def index
    # turn user's list of bills:
    # [bill1, bill2, bill3]
    # into this list of bill occurrences (combo of bill and date):
    # [[bill1_date1, bill1_date2, bill1_date3], [bill2_date1, bill2_date2, bill2_date3], [bill3_date1, bill3_date2, bill3_date3]]
    # flattened:
    # [bill1_date1, bill1_date2, bill1_date3, bill2_date1, bill2_date2, bill3_date3, bill3_date1, bill3_date2, bill3_date3]
    @bill_occurrences = current_user.bills.map do |bill|
      # bill = each user's bill
      bill.dates.map do |date|
        # date = an occurrence date for a bill
        bill_occurrence = bill.clone
        bill_occurrence.date = date
        # bill_occurrence = the occurrence of a bill
        bill_occurrence
      end
    end.flatten
    @bills_by_date = @bill_occurrences.group_by(&:date)

    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    #Added search feature below
    @bills = Bill.search(params[:search])


  end

  def list
      @bills = Bill.search(params[:search])
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @date = params[:date]
    @providers = Provider.all
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json

  def create
    @bill = Bill.new(bill_params)
    #sets new bill equal to the id of the current user signed in.
    @bill.user_id = current_user.id
   
    
    respond_to do |format|
      if @bill.save 
        # send_text_message
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :duedate, :category_id, :provider_id, :paid, :every, :interval, :contact_method, :notes)
    end
end

app/helpers/bills_helper.rb
module BillsHelper

end

app/views/bills/_edit.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form for editing bills -->
  <div class="field" id="coffee">
    <%= f.label :duedate %><br>
    <%= f.text_field :duedate %>
  </div>
  <div class="field" id="cat">
    <!-- Drop Down menu for categories -->
    <%= f.label :category_id %><br>
    <%= select_tag "categories", options_for_select(Category.order(:name).map(&:name))%>
  </div>
  <div class="field" id="pro">
    <!-- Drop Down menu for providers -->
    <%= f.label :provider %><br>
    <%= f.grouped_collection_select :provider_id, Category.order(:name), :providers, :name, :id, :name%>
  </div>
  <div class="field">
    <!-- Drop Down menu for recurrence options -->
    <%= f.label :Repeat %><br>
    <%= f.select :every, [["Monthly", "month"],["Yearly", "year"]] %>
  </div>
  <div class="field">
    <!-- Drop Down menu for recurrence options -->
    <%= f.label :contact_method %><br>
    <%= f.select :contact_method, [["Text", "text"],["Phone Call", "phone call"],["Both", "both"]] %>
  </div><br>
  <div class="field">
    <%= f.label "Paid Status" %>
    <%= f.check_box :paid %>
  </div>
  <div class="actions">
    <%= f.submit "Update", class: 'btn btn-large btn-primary'%>
  </div>
<% end %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
<% if @bill.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

  <ul>
    <% @bill.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- Brand New Bill Form -->
<div class="field">
  <!-- Drop Down menu for categories -->
  <%= f.label :category_id %><br>
  <%= select_tag "categories", options_for_select(Category.order(:name).map(&:name))%>
</div><br>
<div class="field">
  <!-- Drop Down menu for providers -->
  <%= f.label :provider %><br>
  <%= f.grouped_collection_select :provider_id, Category.order(:name), :providers, :name, :id, :name%>
</div><br>
<div class="field">
  <%= f.label :duedate %><br>
  <%= f.text_field :duedate %>
</div><br>
<div class="field">
  <!-- Drop Down menu for recurrence options -->
  <%= f.label :Repeat %><br>
  <%= f.select :every, [["Once a Month", "month"],["Once a year", "year"],["Every Two Weeks","every two weeks"],["Every six Months","twice a year"]] %>
</div><br>

<div class="field">
  <!-- Drop Down menu for recurrence options -->
  <%= f.label :contact_method %><br>
  <%= f.select :contact_method, [["Text", "text"],["Phone Call", "phone call"],["Email", "email"]] %>
</div><br>
<div class="field">
  <%= f.label :"Notes (optional)" %><br>
  <%= f.text_field :notes %>
</div><br>
<div class="field">
  <%= f.hidden_field :paid, value: false %>
</div>
<div class="actions">
  <%= f.submit "Create", class: 'btn btn-primary btn-block'%>
</div> 
<% end %>

app/views/bills/_form_edit.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form for editing bills -->
  <div class="admin" class="field" id="coffee">
    <%= f.label :duedate %><br>
    <%= f.text_field :duedate %>
  </div>
 <!-- Drop Down menu for recurrence options -->
  <div class="admin" class="field">
    <%= f.label :Repeat %><br>
    <%= f.select :every, [["Monthly", "month"],["Yearly", "year"],["Every Two Weeks","every two weeks"],["Twice A Year","twice a year"]] %>  </div>
  <div class="admin" class="field">
    <!-- Drop Down menu for recurrence options -->
    <%= f.label :contact_method %><br>
    <%= f.select :contact_method, [["Text", "text"],["Phone Call", "phone call"],["Email", "email"]] %>
  </div><br>
  <div class="admin" class="field">
    <%= f.label "Paid Status" %>
    <%= f.check_box :paid %>
  </div>
  <div class="admin" class="actions">
    <%= f.submit "Update", class: 'btn btn-large btn-primary'%>
  </div>
<% end %>

app/views/bills/_form_paid.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Paid checkbox when showing bill to mark as paid -->
  <% if @bill.paid == false %>
     <div class="field">
      <%= f.check_box :paid %> Mark as Paid
    </div>
     <div class="actions">
      <br>
    <%= f.submit "Update", class: 'btn btn-default btn-xs'%>
    </div>
    <% end %>
  <% end %>

app/views/bills/edit.html.erb
<h1 class="admin">Edit</h1>






<%= render 'form_edit'%>
<div class="admin">
<%= link_to 'Show', @bill %> |
<%= link_to 'Calendar', bills_path %>
</div>

app/views/bills/index.html.erb
<% @body_class = "calender" %>


<div id="bills">
  <h2 id="month">
    

    <%= link_to "<", date: @date.prev_month %>
  
    <span class='bounceIn' ><%= @date.strftime("%B %Y") %></span>
    <%= link_to ">", date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @bills_by_date[date]%>
      <ul>
        <% @bills_by_date[date].each do |bill| %>
          <li><%= link_to bill.provider.name, bill_path(bill, date: date) %></li>
        <% end %>
      </ul>
    <% end %> 
  <% end %>
</div>

app/views/bills/list.html.erb
<% if current_user.bills.empty? %>

<h2 class="center_bill_list_h">You have not added any bills</h2>

<% else %>

<h1 class='bounceIn'>All Bills</h1>
<table class="table table-hover table-striped">
  <tbody>
  <thead>
    <tr>
      <th>Provider</th>
      <th>Category</th>
      <th>Payment Status</th>
      <th>Recurrence</th>
      <th>Reminder Method</th>
    </tr>
  </thead>
<tr>
<% current_user.bills.each do |bill| %>
<tr onclick='location.href="<%= bill_path(bill) %>"'>
<td><%= bill.provider.name %></td>
<td><%= bill.provider.category.name %></td>
<td>
  <% if bill.paid %>
  <%= "Paid" %>
  <% else %>
  <%= "Not Paid" %>
  <% end %>
</td>
<td><%= bill.every %></td>
<td><%= bill.contact_method %></td>
</tr>
<% end %>
  </tbody>
    </table>

<% end %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Calendar', bills_path %>

app/views/bills/show.html.erb
<p class = "billshow">
  <strong class = "billshowcolor">Category</strong>
  <%= @bill.category.name %>
</p>

<p class = "billshow">
  <%= @date %>
</p>

<p class = "billshow">
  <% if @bill.notes.empty? %>
  <% else %>
      <strong class = "billshowcolor">Notes</strong>
      <%= @bill.notes %>
</p>
  <% end %>

<p class = "billshow">
  <strong class = "billshowcolor">Provider</strong>
  <% @providers.each do |provider| %>
    <% if provider.id == @bill.provider_id %>
    <%= provider.name %>
    <%end%>
  <% end %>
</p>

<p class = "billshow">
  <strong class = "billshowcolor">Payment Status</strong> 
    <% if @bill.paid %>
      <%= "Paid" %>
    <% else %>
      <%= "Not Paid" %>
     <div class = "billshow"> <%= render 'form_paid' %></div>
  <% end %> 
</p> 

<i ></i>

<p class = "billshow">
 <%= link_to "", @bill.provider.url, class: "fa fa-credit-card fa-2x", target: 'blank' %>
</p>
<!-- End of Show page

Edit Modal -->
<p class = "billshow">
<%= link_to '', edit_bill_path(@bill), class: "fa fa-pencil-square-o" %> |
<%= link_to @bill, method: :delete do%>
  <span class="fa fa-trash-o"></span>
          <% end %>
<br>
</p>
      