config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users
  
  get 'admin_dashboard/index'

  get 'about/howitworks'

  get 'about/aboutus'

  get 'about/terms'

  get 'admin_dashboard/all_bills'

  get 'admin_dashboard/all_users'

  get 'admin_dashboard/phone_data'

  resources :providers

  get 'sendtext/index'

  root "home#index"

  get 'bills/list'

  resources :bills

  resources :categories do
    resources :providers
  end
  
  resources :dashboard
  

  

end

app/views/layouts/admin_dashboard.erb
<!DOCTYPE html>
<html>
<head class="head">
  <title>Reminderapp</title>
  
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="background">

  <nav class="navbar navbar-fmn" role="navigation">
    <div class="container">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Forget Me Not", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
           Views
           <span class="caret"></span></a>
           <ul class="dropdown-menu" role="menu">  
             <li><%= link_to 'Calendar', bills_path%></li>
             <li><%= link_to 'Bill List', bills_list_path%></li>
           </ul>
         </li>
         
        <!--  new bill modal -->

         <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm">New</a> </li>
         <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <% @event_recurrence = EventRecurrence.new %>
              <% @bill = Bill.new %>
              <%= render 'bills/form' %>
            </div>
          </div>
        </div>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text"></p>
        <li><%= link_to "How It Works", about_howitworks_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 

            <%= current_user.first_name %> <%= current_user.last_name %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">

              <li><%= link_to 'Edit profile', edit_user_registration_path, :method => :get %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
        <% else %>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up", new_user_registration_path %></li> 
          <li><%= link_to "Log in", new_user_session_path %></li>
        </ul>
        <% end %>



      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

<!-- footer -->

  <footer class="navbar navbar-fmn-footer">
    <div class="container">
      <p class="navbar-text pull-left">Copyright&#169 2014. ForgetMeNot</p>

      <%= link_to "http://www.facebook.com" do %>
      <%= image_tag "fb.png", size: '40'%> 
      <% end %>
      <%= link_to "http://www.twitter.com" do %>
      <%= image_tag "twitter.png", size: '40'%> 
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About Us", about_aboutus_path %></li>
      </ul>

    </div>
  </footer>

  
</body>
</html>

app/views/layouts/admin_dashboard.html.erb
<!DOCTYPE html>
<html>
<head class="head">
  <title>Reminderapp</title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="background_admin">

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ForgetMeNot", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              Administrator Views
              <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">  
                <li><%= link_to 'All Users', admin_dashboard_all_users_path%></li>
                <li><%= link_to 'All Bills', admin_dashboard_all_bills_path%></li>
                <li><%= link_to 'Phone Data', admin_dashboard_phone_data_path%></li>
                <li><%= link_to 'Analytics', admin_dashboard_index_path%></li>
              </ul>
            </li>

            <!--  new bill modal -->

            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm">New</a> </li>
            <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <% @event_recurrence = EventRecurrence.new %>
                  <% @bill = Bill.new %>
                  <%= render 'bills/form' %>
                </div>
              </div>
            </div>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text"></p>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 

                <%= current_user.first_name %> <%= current_user.last_name %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">

                  <li><%= link_to 'Edit profile', edit_user_registration_path, :method => :get %></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
            <% else %>

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign up", new_user_registration_path %></li> 
              <li><%= link_to "Log in", new_user_session_path %></li>
            </ul>
            <% end %>



          </div><!-- /.navbar-collapse -->
        </div>
      </nav>

      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <div class="container">
        <%= yield %>
      </div>

      <footer class="navbar navbar-fmn-footer">
        <div class="container">
          <p class="navbar-text pull-left">Copyright &#169 2014. ForgetMeNot</p>

          <%= link_to "http://www.facebook.com" do %>
          <%= image_tag "facebook-512.png", size: '40'%> 
          <% end %>
          <%= link_to "http://www.twitter.com" do %>
          <%= image_tag "twitter-512.png", size: '40'%> 
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "Admin", admin_dashboard_index_path %></li>
            <% end %>
            <li><%= link_to "About Us", about_aboutus_path %></li>
          </ul>

        </div>
      </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head class="head">
  <title>Reminderapp</title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body <%== "class='background #{@body_class}'" %> >


  <nav class="navbar navbar-fmn" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ForgetMeNot", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              Views
              <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">  
                <li><%= link_to 'Calendar', bills_path%></li>
                <li><%= link_to 'Bill List', bills_list_path%></li>
              </ul>
            </li>

            <!--  new bill modal -->

            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm">New</a> </li>
            <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <% @event_recurrence = EventRecurrence.new %>
                  <% @bill = Bill.new %>
                  <%= render 'bills/form' %>
                </div>
              </div>
            </div>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text"></p>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 

                <%= current_user.first_name %> <%= current_user.last_name %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">

                  <li><%= link_to 'Edit profile', edit_user_registration_path, :method => :get %></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
            <% else %>

            <ul class="nav navbar-nav navbar-right">
             
              <li><%= link_to "Sign in", new_user_session_path %></li>
            </ul>
            <% end %>



          </div><!-- /.navbar-collapse -->
        </div>
      </nav>

      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <div class="container">
        <%= yield %>
      </div>

      <!-- footer -->

      <footer class="navbar navbar-fmn-footer">
        <div class="container">
          <p class="navbar-text pull-left">Copyright &#169 2014. ForgetMeNot</p>

          <%= link_to "http://www.facebook.com" do %>
          <%= image_tag "facebook-512.png", size: '40'%> 
          <% end %>
          <%= link_to "http://www.twitter.com" do %>
          <%= image_tag "twitter-512.png", size: '40'%> 
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "Admin", admin_dashboard_index_path %></li>
            <% end %>
            <li><%= link_to "About Us", about_aboutus_path %></li>
          </ul>

        </div>
      </footer>


    </body>
    </html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head class="head">
  <title>Reminderapp</title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body <%== "class='background #{@body_class}'" %> >


  <nav class="navbar-home navbar-fmn" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div>
        <%= link_to "ForgetMeNot", root_path, class: "navbar-brand" %>
      </div>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              Views
              <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">  
                <li><%= link_to 'Calendar', bills_path%></li>
                <li><%= link_to 'Bill List', bills_list_path%></li>
              </ul>
            </li>

            <!--  new bill modal -->

            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm">New</a> </li>
            <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <% @event_recurrence = EventRecurrence.new %>
                  <% @bill = Bill.new %>
                  <%= render 'bills/form' %>
                </div>
              </div>
            </div>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text"></p>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 

                <%= current_user.first_name %> <%= current_user.last_name %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">

                  <li><%= link_to 'Edit profile', edit_user_registration_path, :method => :get %></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
            <% else %>

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign in", new_user_session_path %></li>
            </ul>
            <% end %>



          </div><!-- /.navbar-collapse -->
        </div>
      </nav>

      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      
        <%= yield %>
      

      <!-- footer -->

      <footer class="navbar-home navbar-fmn-footer">
        <div class="container">
          <p class="navbar-text pull-left">Copyright &#169 2014. ForgetMeNot</p>

          <%= link_to "http://www.facebook.com" do %>
          <%= image_tag "facebook-512.png", size: '40'%> 
          <% end %>
          <%= link_to "http://www.twitter.com" do %>
          <%= image_tag "twitter-512.png", size: '40'%> 
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "Admin", admin_dashboard_index_path %></li>
            <% end %>
            <li><%= link_to "About Us", about_aboutus_path %></li>
          </ul>

        </div>
      </footer>


    </body>
    </html>